; option for changing budget display: flamingo, intraw, accurate, or basic
budget=flamingo
; option for changing keyboard layout, current support for qwerty, azerty, and jcuken
keyboard=qwerty
; option for changing language used for searching, current support for en, de, es, esmx, fr, it, pl, ptbr, and ru
language=en
; for keys, use the constants listed at https://help.adobe.com/en_US/air/reference/html/flash/ui/Keyboard.html
; NUMBER_0..NUMBER_9, NUMPAD_0..NUMPAD_9, F1..F12, etc.
; key for starting search
searchkey=F5
; key for selecting previous match
prevkey=F6
; key for selecting next match
nextkey=F7
; key for stopping search
endkey=F8
; key for toggling new
togglekey=F9
; key for toggling flamingo units
budgetkey=F10
